name: jupyter-actions
channels:
    - conda-forge
dependencies:
  - jupyter=1.0
  - nbformat
  - nbconvert
  - numpy=1.22.3
  - scikit-learn=1.1.3
  - matplotlib=3.5.3
  - keras=2.9.0
  - tensorflow=2.9.1
  - requests=2.24.0
  - pytest
